### ISSUE TITLE
It seems this is broken now...

### ISSUE THREAD

**Issue by ilikenwf** [ilikenwf/plugin.video.rumble.matrix#5]
I'm guessing rumble changed their web code somehow.

**Comment by azzy9** [comment]
PR#4 should now fix this

**Comment by ohmichael** [comment]
broken for me too what's going on here...

**Comment by azzy9** [comment]
> broken for me too what's going on here...

Rumble have changed the layout of the site, the Kodi rumble plugins scrape the site, so require the regex to be correct

**Comment by ohmichael** [comment]
Hopefully someone like the person who originally created the plugin is on this working on it - can't find many people who want to work on a rumble plugin especially since nexus is out and the version above that omega I believe is being worked on too eventually - matrix will be obsolete soon. But if you're the one who made rumble.matrix please make an updated version.
I use this plugin lots - thank you. I know it's not easy to code so if you want to take your time it's fine with me just keep me in the loop.

**Comment by azzy9** [comment]
I didn't fork it, but have submitted a fix, it has been merged into the testing branch of this fork.

**Comment by ohmichael** [comment]
oh I know I see the fix now thanks lots you are a life saver.

**Comment by azzy9** [comment]
no problem, it would be awesome to report back if you see any issues with the testing branch :)

**Comment by ohmichael** [comment]
Haven't tested it yet but will do as soon as I send it over to my nvidia shield tv box then merge files then I'll see how it operates then I'll let you know. thx for everything. Hopefully rumble doesn't change their coding again. It's sad when they do this stuff. I remember bitchute used to change their coding all the time. Would get me so angry lol. But I find rumble to be better than bitchute.

**Comment by ohmichael** [comment]
I’m receiving an error upon opening up the addon & the shortcut to channels I have set are also giving an error popup.

**Comment by azzy9** [comment]
Would it be possible to post an error log?

**Comment by azzy9** [comment]
I thought it might be an issue on Kodi 20 on android devices since you mentioned an nvidea shield. I just installed and ran it on my android phone with Kodi 20 with no issue. So a couple of things that I could think of, issue with dependencies or something gone weird with the favourites file.

**Comment by ohmichael** [comment]
I don’t feel really comfortable sharing my logs with anyone but to get rumble working I’ll do it btw I’ve never shared my logs with anyone which file is it & how do I prevent sensitive information from being shown in the logs?

**Comment by azzy9** [comment]
https://kodi.wiki/view/Log_file

The log file usually only includes version information, plugins installed and actions taken for your current session including warnings & the errors. Usually the only identifiable information is if you have your name in your folder path (as warned about in the link above)

**Comment by ohmichael** [comment]
I took a chance please remove this comment once you view it thx
I looked it over & I feel pretty confident no one can retrieve anything besides a fix for rumble
Error Log: https://paste.kodi.tv/sihozelaye.kodi

**Comment by azzy9** [comment]
Thank you, looking at it now. You will need to edit & delete the link since I don't have the permissions to do it.

**Comment by azzy9** [comment]
@ohmichael had a look,

Error Contents: unindent does not match any outer indentation level (main.py, line 556)
File "/files/.kodi/addons/plugin.video.rumble.matrix/main.py", line 556
                                                       else:
                                                           ^
IndentationError: unindent does not match any outer indentation level

saying there is an issue on line 556 with indents, I'm confused as there is no line 556 in the testing branch?

I created a zip from the testing branch to see if that is any better: https://mega.nz/file/JVkT2JzY#gFyuYf_oGFOvtUTfqrOWEY3m8coOcp_9y-n9wZvzLc0

**Comment by ohmichael** [comment]
Let me know when you look again @azzy9 so I can delete
Kodi Log: https://paste.kodi.tv/zifiyufehe.kodi
Rumble opens up but nothing is playable & the log will show that.
When I go into a persons profile for example thesaltycracker as it shows in the log it opens like before but no video will play - just spins & freezes up.
I had to force exit out of kodi after 15-30 seconds to give the log enough time to gather information.

**Comment by azzy9** [comment]
@ohmichael I have got the link now, so you can delete it. unfortunately the log isn't showing me anything wrong with the plugin (lots of errors from old repos that no longer exist though).

It would help if I could replicate the issue.

I need to go to bed now so will have a look tomorrow to see if I can find anything

**Comment by ohmichael** [comment]
Yeah I know I have like 240 kodi plugins not counting their dependencies & counterparts ha I’m a hoarder I need to clean up but they wouldn’t affect rumble or anything I also have the automatic startup turned off on many plugins with the help of autoruns so that wouldn’t be affecting anything either I don’t think anything I did would affect it because it worked before but yeah same here I was just trying to help hopefully you have all the information you need. Night. Enjoy yourself & get back to me whenever if you need a log or a tester.

**Comment by azzy9** [comment]
@ohmichael

I have tried again on a similar setup as yours as shown in the logs (Android 64bit, Kodi 19.5) but unfortunately still cannot replicate the issue.

Some stuff to try:

Uninstall all the dead repos as they seem to be still checking them when you are testing the plugin.

Try it on another device to make sure there is nothing on your network or internet that is causing the issue.

You can also try enabling debug mode then try again to see if there is any more information in the log file.
To enable debug mode:
https://kodi.wiki/view/Log_file/Easy
Note: disable debug mode as soon as you have done the test otherwise will get very large very quick.

**Comment by ohmichael** [comment]
Good luck then I’m not removing anything sounds like apple telling me to remove my vpns from my iPhone when it was their end messing up lulz but anyways I’m positive it’s nothing I did or have on my system because it worked on the other version before rumble changed their format - if you release this I would put a note next to it that it’s experimental & may not play videos but will open up for the most part for some nvidia shield tv users as that’s what I use. Can’t say the same for phone users Xbox or any other device - just what I use - it’s a shame I couldn’t get it to work - I can airplay or chromecast it I guess - you can close this ticket but it was never my ticket to begin with I just replied & tried to help by adding my two cents - well that’s all I have to offer then - good day to you.

**Comment by azzy9** [comment]
rather than uninstalling them, you could try disabling them so they are not trying to do loads look-ups to 404 pages. I know somebody that has a shield so I could ask them if I could try at some point.
The issue is that if there is no error and no way to replicate the issue, then there is nothing I can do.
But thank you for testing for me even if we couldn't get it working in the end.

**Comment by ilikenwf** [comment]
@azzy9  thanks for fixing, works here.

@ohmichael, you may have better luck grabbing the testing.zip from github. Sometimes Kodi rejects zips and it is hard to notice.

**Comment by ohmichael** [comment]
I grabbed it other day I tagged you on oneplayhd help ticket should of done it here too - thx for everything.
